[build]
  functions = "src"
  publish = "public/"

[functions]
  included_files = ["views/**"]

#[[redirects]]
 # from = "/*"
  #to = "/.netlify/functions/api/:splat"


  

[dev]
  functions = "src"
  publish = "public/"
  targetPort = 3000