[build]
  functions = "src"
  publish = "public/"

[functions]
  included_files = ["views/**","public/**"]

[[redirects]]
from = "/*"
to = "/.netlify/functions/api/:splat"


  

[dev]
  functions = "src"
  #publish = "public/"
  targetPort = 3000

  [[redirects]]
    from="http://127.0.0.1:3000/*"
    to="http://127.0.0.1:8888/:splat"